[window]
opacity = 0.9

[window.padding]
x = 10
y = 10

[colors]

[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

[colors.cursor]
text = '#1a1b26'
cursor = '#a9b1d6'

[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#4fd6be'
white = '#a9b1d6'

[colors.bright]
black = '#444b6a'
red = '#ff7a91'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb2cb'
